name: Git Flow Sync
on:
  pull_request:
    types: [closed]
    branches: [main, development]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup and Sync
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Get info
          BRANCH="${{ github.event.pull_request.head.ref }}"
          TARGET="${{ github.event.pull_request.base.ref }}"
          
          # Branch protection validation
          if [ "$TARGET" = "main" ]; then
            # Main branch: only hotfix/* and release/* allowed
            if [[ ! "$BRANCH" =~ ^(hotfix|release)/ ]]; then
              echo "❌ INVALID MERGE TO MAIN!"
              echo "❌ Branch: $BRANCH"
              echo "❌ Only hotfix/* and release/* can merge to main"
              # Revert the merge (if possible) or create issue
              gh issue create --title "🚨 Invalid merge to main: $BRANCH" --body "Branch $BRANCH was merged to main but only hotfix/* and release/* are allowed!"
              exit 1
            fi
          elif [ "$TARGET" = "development" ]; then
            # Development branch: only hotfix/*, release/*, feature/* allowed  
            if [[ ! "$BRANCH" =~ ^(hotfix|release|feature)/ ]]; then
              echo "❌ INVALID MERGE TO DEVELOPMENT!"
              echo "❌ Branch: $BRANCH"
              echo "❌ Only hotfix/*, release/*, and feature/* can merge to development"
              # Revert the merge (if possible) or create issue
              gh issue create --title "🚨 Invalid merge to development: $BRANCH" --body "Branch $BRANCH was merged to development but only hotfix/*, release/*, and feature/* are allowed!"
              exit 1
            fi
          fi
          
          # Check if hotfix or release for sync
          if [[ ! "$BRANCH" =~ ^(hotfix|release)/ ]]; then
            echo "Not a hotfix or release branch - no sync needed"
            exit 0
          fi
